import RPi.GPIO as GPIO
import time
GPIO.setmode(GPIO.BOARD)
GPIO.setup(11, GPIO.OUT)
GPIO.setup(13, GPIO.OUT)
GPIO.setup(16, GPIO.OUT)

up = GPIO.PWM(11, 200)
down = GPIO.PWM(13, 200)
right = GPIO.PWM(16, 200)
up.start(100)
time.sleep(3)
right.start(100)
time.sleep(0.5)
up.start(0)
time.sleep(0.1)
down.start(100)
time.sleep(1)
right.start(0)
down.start(0)
up.stop()
down.stop()
right.stop()
GPIO.cleanup()
